/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpecialItemGroupRouteImport } from './routes/special-item-group'
import { Route as IndexRouteImport } from './routes/index'

const SpecialItemGroupRoute = SpecialItemGroupRouteImport.update({
  id: '/special-item-group',
  path: '/special-item-group',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/special-item-group': typeof SpecialItemGroupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/special-item-group': typeof SpecialItemGroupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/special-item-group': typeof SpecialItemGroupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/special-item-group'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/special-item-group'
  id: '__root__' | '/' | '/special-item-group'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpecialItemGroupRoute: typeof SpecialItemGroupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/special-item-group': {
      id: '/special-item-group'
      path: '/special-item-group'
      fullPath: '/special-item-group'
      preLoaderRoute: typeof SpecialItemGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpecialItemGroupRoute: SpecialItemGroupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
